default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: bun-install
        name: pnpm install (frozen)
        entry: pnpm install --frozen-lockfile
        language: system
        pass_filenames: false
        stages:
          - pre-commit
        always_run: true

      - id: lint-staged
        name: lint staged
        entry: pnpm lint-staged
        language: system
        pass_filenames: false
        stages:
          - pre-commit
        always_run: true
